version: '3.3'

services:
    debian-sftp:
        image: nmainiero/docker-debian-sftp:main
        restart: unless-stopped
        hostname: debian-sftp
        container_name: debian-sftp
        ports:
            - "2800:22"
        stdin_open: true
        tty: true

